name: Test debug
on:
  push:
    branches:
      - 'main'
      - 'releases/**'
  pull_request:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./ # theofficialgman/arm-runner-action@HEAD
      with:
        commands: |
          set -o | egrep 'xtrace\s+on'
