name: Test architecture matrix
on:
  push:
    branches:
      - 'main'
      - 'releases/**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [armv7l, aarch64]
        include:
        - arch: armv7l
          base_image: raspios_lite:latest
        - arch: aarch64
          base_image: raspios_lite_arm64:latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./ # theofficialgman/arm-runner-action@HEAD
      with:
        base_image: ${{ matrix.base_image }}
        commands: |
            test `uname -m` = ${{ matrix.arch }}
